In [1]:
import numpy as np

第一章 线性方程组与矩阵

第一章 第一节 矩阵的概念及运算

第一章 第一节 一、矩阵的定义

In [2]:
# ndarray.dtype：存储了数组保存的元素的类型。float32
# ndarray.ndim：它是一个整数，保存了数组的维度，即多少个轴
# ndarray.shape：它是一个整数的元组，每个元素一一对应地保存了数组某个维度的大小（即某个轴的长度）。
# ndarray.strides：它是一个整数的元组，每个元素保存着每个轴上相邻两个元素的地址差。即当某个轴的下标增加1 时，数据存储区中的指针增加的字节数
# ndarray.data：它指向数组的数据的存储区
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1.shape, array1.dtype, array1.ndim, array1.strides, array1.data

((3, 3), dtype('int32'), 2, (12, 4), <memory at 0x000002814D1145F0>)

第一章 第一节 二、矩阵的线性运算

In [3]:
#加法
array2 = array1
array3 = array1 + array2
array3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
#数乘
array4 = 3 * array1
array4

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

第一章 第一节 三、矩阵的乘法

In [5]:
#实践发现dot和matmul都是矩阵相乘
array5 = np.dot(array1,array2)
array5m = np.matmul(array1,array2)
array5,array5m

(array([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]]),
 array([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]]))

第一章 第一节 四、矩阵的转置

In [6]:
array6 = array1.T
array6

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

第一章 第二节 分块矩阵

第一章 第三节 线性方程组与矩阵的初等变换

第一章 第四节 初等矩阵与矩阵的逆矩阵

In [7]:
array1Inv = np.linalg.inv(array1)
array1Inv

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

第二章 方阵的行列式

第二章 第一节 行列式的定义

第二章 第一节 一、排列

第二章 第一节 二、n阶行列式

第二章 第一节 三、几类特殊的n阶行列式的值

第二章 第二节 行列式的性质

第二章 第二节 一、行列式的性质

第二章 第二节 二、行列式的计算举例

In [8]:
#行列式的计算
array1Det = np.linalg.det(array1)
array1Det

-9.51619735392994e-16

第二章 第二节 三、方阵可逆的充要条件

第二章 第三节 行列式按行（列）展开

第二章 第三节 一、余子式与代数余子式

第二章 第三节 二、行列式按行（列）展开

第二章 第四节 矩阵求逆公式与克莱姆法则

第二章 第四节 一、伴随矩阵与矩阵的求逆公式

第二章 第四节 二、克莱姆法则

第三章 向量空间与线性方程组解的结构

第三章 第一节 向量组及其线性组合

第三章 第一节 一、向量的概念及运算

In [9]:
row_vector = np.array([1,2,3])
col_vector = np.array([[4],
                       [5],
                       [6]])
#向量可以看成行矩阵或列矩阵

第三章 第一节 二、向量组及其线性组合

In [10]:
row_vector1 = np.array([1,2,3])
row_vector2 = np.array([1,2,3])
row_vector3 = np.array([1,2,3])
# row_vector1,row_vector2,row_vector3称为一个向量组

第三章 第一节 三、向量组的等价

第三章 第二节 向量组的线性相关性

第三章 第二节 一、向量组的线性相关与线性无关

第三章 第二节 二、向量组线性相关性的一些重要结论

第三章 第三节 向量组的秩与矩阵的秩

第三章 第三节 一、向量组秩的概念

In [11]:
#向量组A的任意一个极大无关组所含向量的个数，称为这个向量组的秩，记为RA（A是下角标）

第三章 第三节 二、矩阵秩的概念

第三章 第三节 三、矩阵秩的求法

In [12]:
Rarray1 = np.linalg.matrix_rank(array1)
Rarray1

2

In [13]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

第三章 第三节 四、向量组的秩与矩阵的秩的关系

In [14]:
#矩阵的行向量组的秩与它的列向量组的秩相等，都等于矩阵的秩

第三章 第四节 线性方程组解的结构

第三章 第四节 一、线性方程组有解的判定定理

第三章 第四节 二、齐次线性方程组解的结构

第三章 第四节 三、非齐次线性方程组解的结构

In [15]:
#设有以下方程组
#2x + 3y = 13
#4x + y = 11
#定义系数矩阵A
A = np.array([[2,3],
              [4,1]])
#定义右侧向量b
b = np.array([13,11])
#使用numpy.linalg.solve()解线性方程组
result = np.linalg.solve(A,b)
result

array([2., 3.])

第三章 第五节 一、向量空间及其子空间

第三章 第五节 二、向量空间的基、维数与坐标

第三章 第五节 三、基变换与坐标变换

第四章 相似矩阵及二次型

第四章 第一节 向量的内积、长度及正交性

第四章 第一节 一、向量的内积、长度

In [18]:
# 求向量的内积
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
inner_product = np.dot(vector1,vector2)
inner_product

32

In [21]:
# 求向量的长度
length = np.linalg.linalg.norm(vector1)
length

3.7416573867739413

第四章 第一节 二、正交向量组

第四章 第一节 三、施密特正交化过程

第四章 第一节 四、正交矩阵

第四章 第二节 方阵的特征值与特征向量

第四章 第二节 一、方阵的特征值与特征向量的概念及其求法

In [34]:
matrix = np.array([[-1,2,0],[0,3,0],[2,1,-1]])
eigenvalues,eigenvectors = np.linalg.eig(matrix)
#求特征值和特征向量
eigenvalues,eigenvectors

(array([-1., -1.,  3.]),
 array([[ 0.00000000e+00,  1.11022302e-16,  4.08248290e-01],
        [ 0.00000000e+00,  0.00000000e+00,  8.16496581e-01],
        [ 1.00000000e+00, -1.00000000e+00,  4.08248290e-01]]))

第四章 第二节 方阵的特征值与特征向量的性质

第四章 第三节 相似矩阵

第四章 第三节 一、方阵相似的定义和性质

第四章 第三节 二、方阵的相似对角化

第四章 第四节 实对称矩阵的相似对角化

第四章 第四节 一、实对称矩阵的特征值与特征向量的性质

第四章 第四节 二、实对称矩阵的相似对角化