In [1]:
import numpy as np

第一章 线性方程组与矩阵

第一章 第一节 矩阵的概念及运算

第一章 第一节 一、矩阵的定义

ndarray.dtype：存储了数组保存的元素的类型。float32
ndarray.ndim：它是一个整数，保存了数组的维度，即多少个轴
ndarray.shape：它是一个整数的元组，每个元素一一对应地保存了数组某个维度的大小（即某个轴的长度）。
ndarray.strides：它是一个整数的元组，每个元素保存着每个轴上相邻两个元素的地址差。即当某个轴的下标增加1 时，数据存储区中的指针增加的字节数
ndarray.data：它指向数组的数据的存储区

In [2]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1.shape, array1.dtype, array1.ndim, array1.strides, array1.data

((3, 3), dtype('int32'), 2, (12, 4), <memory at 0x000001B5D59CD5F0>)

第一章 第一节 二、矩阵的线性运算

In [3]:
#加法
array2 = array1
array3 = array1 + array2
array3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
#数乘
array4 = 3 * array1
array4

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

第一章 第一节 三、矩阵的乘法

In [6]:
array5 = np.dot(array1,array2)
array5

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

第一章 第一节 四、矩阵的转置

In [7]:
array6 = array1.T
array6

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

第一章 第二节 分块矩阵

第一章 第三节 线性方程组与矩阵的初等变换

第一章 第四节 初等矩阵与矩阵的逆矩阵

In [8]:
array1Inv = np.linalg.inv(array1)
array1Inv

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])